"""Shared paths and controlled vocabularies for the Team 38 pipeline.

Single source of truth for where files live and what strings mean, so the
cleaning code, the SQL validation, and docs/data-dictionary.md cannot drift
apart. Every reason code here should map to a problem ID in
docs/data-quality-problems.md and a rule in docs/cleaning-rules.md.

This module is deliberately side-effect free: it *declares* paths but never
creates directories. Run directories are created on demand by
provenance.write_step(), so adding a cleaning function needs no bookkeeping
here -- see src/README.md.
"""

from __future__ import annotations

import string
from dataclasses import dataclass
from pathlib import Path
from typing import Final

# --- Paths --------------------------------------------------------------
PROJECT_ROOT: Final = Path(__file__).resolve().parent.parent
DATA_DIR: Final = PROJECT_ROOT / "data"
SQL_DIR: Final = PROJECT_ROOT / "sql"

# Cross-table outputs, owned by no single source table.
REPORTS_DIR: Final = DATA_DIR / "reports"   # validation + violation exports
DB_PATH: Final = DATA_DIR / "cs513_team38.sqlite"

# data/final/ belongs to the SQL workflow (Step 9: final_menu.csv,
# final_item.csv). Those are joins across tables, so they live at the root and
# no source table has a final/ directory of its own.
FINAL_DIR: Final = DATA_DIR / "final"


@dataclass(frozen=True)
class TablePaths:
    """Where one source table's files live.

    Every table has the same shape on disk::

        data/<dir_name>/raw/<Name>.csv                     immutable input
        data/<dir_name>/interim/open-refine/<Name>_OR.csv  OpenRefine export
        data/<dir_name>/interim/func-<step>/               one per cleaning function
        data/<dir_name>/interim/cleaned/<Name>_cleaned.csv load-ready for SQLite

    `raw/` and `interim/open-refine/` arrive in the shared input zip; everything
    else is regenerated by `python -m src.run_pipeline`.

    There is deliberately no per-table `final/`. Everything this pipeline writes
    is intermediate as far as the project is concerned -- `data/final/` holds the
    SQL workflow's outputs, which are joins across tables.
    """

    key: str        # dict key / python identifier, e.g. "menu_item"
    dir_name: str   # directory on disk, e.g. "menu-item"
    name: str       # CSV basename stem, e.g. "MenuItem"

    @property
    def root(self) -> Path:
        return DATA_DIR / self.dir_name

    @property
    def raw_dir(self) -> Path:
        return self.root / "raw"

    @property
    def interim_dir(self) -> Path:
        return self.root / "interim"

    @property
    def cleaned_dir(self) -> Path:
        return self.interim_dir / "cleaned"

    @property
    def raw_file(self) -> Path:
        return self.raw_dir / f"{self.name}.csv"

    @property
    def or_file(self) -> Path:
        return self.interim_dir / "open-refine" / f"{self.name}_OR.csv"

    @property
    def cleaned_file(self) -> Path:
        """Load-ready CSV: data columns only, no provenance columns.

        The provenance columns exist to explain how a value got there, which is
        a question about this pipeline, not about the data. Carrying them into
        SQLite would put three columns in every staging table that no query
        needs -- they stay in the func-<step>/ snapshots, where they belong.
        """
        return self.cleaned_dir / f"{self.name}_cleaned.csv"

    def func_dir(self, step: str) -> Path:
        """Directory holding one cleaning function's output.

        Returns the path without creating it -- provenance.write_step() owns
        directory creation so that merely referencing a path has no side effect.
        """
        return self.interim_dir / f"func-{step}"


TABLES: Final[dict[str, TablePaths]] = {
    "menu": TablePaths("menu", "menu", "Menu"),
    "menu_page": TablePaths("menu_page", "menu-page", "MenuPage"),
    "menu_item": TablePaths("menu_item", "menu-item", "MenuItem"),
    "dish": TablePaths("dish", "dish", "Dish"),
}

RAW_FILES: Final[dict[str, Path]] = {k: t.raw_file for k, t in TABLES.items()}
OR_FILES: Final[dict[str, Path]] = {k: t.or_file for k, t in TABLES.items()}
CLEANED_FILES: Final[dict[str, Path]] = {k: t.cleaned_file for k, t in TABLES.items()}


# --- Expected shape of the OpenRefine exports ---------------------------
# Asserted on load. The OR files are hand-produced and get re-exported when the
# OpenRefine recipe changes, so a silent column rename would otherwise surface
# much later as a confusing failure inside a cleaning function.
OR_EXPECTED_COLUMNS: Final[dict[str, tuple[str, ...]]] = {
    "menu": ("id", "date", "currency", "status"),
    "menu_page": ("id", "menu_id"),
    "menu_item": ("id", "menu_page_id", "price", "high_price", "dish_id"),
    "dish": ("id", "name", "lowest_price", "highest_price"),
}

# Row counts observed in the exports of 2026-07-28, recorded so a re-export that
# silently changes scope is noticed. Informational -- not asserted.
OR_OBSERVED_ROWS: Final[dict[str, int]] = {
    "menu": 5_236,
    "menu_page": 66_937,
    "menu_item": 1_332_668,
    "dish": 394_297,
}


# --- Provenance ---------------------------------------------------------
# Per-row audit trail. `log` accumulates across every function in a table's
# chain, so the final CSV carries the row's full transformation history.
LOG_COLUMN: Final = "log"
LOG_SEPARATOR: Final = ";"
OMIT_COLUMN: Final = "omit"

SOURCE_FILE_COLUMN: Final = "source_file"
SOURCE_ROW_COLUMN: Final = "source_row_num"

PROVENANCE_COLUMNS: Final = (SOURCE_FILE_COLUMN, SOURCE_ROW_COLUMN, LOG_COLUMN)


def log_tag(column: str, operation: str) -> str:
    """Build one log entry: ``name:uppercased``.

    Tags are `<column>:<operation>` so the Step-5 summary can report cells
    changed *per column* -- splitting on LOG_SEPARATOR then on ":" gives both
    dimensions. Counting without splitting gives wrong numbers; see the open
    question in docs/data-dictionary.md.
    """
    return f"{column}:{operation}"


class Operation:
    """Controlled vocabulary for the operation half of a log tag."""

    # Type coercion
    TO_INT = "to_int"
    TO_DECIMAL_2DP = "to_decimal_2dp"

    # Outlier handling
    WINSORIZED = "winsorized"

    # Text normalization (Dish.name)
    UPPERCASED = "uppercased"
    SPACES_COLLAPSED = "spaces_collapsed"
    TRIMMED = "trimmed"
    PUNCT_TO_SPACE = "punct_to_space"
    PUNCT_REMOVED = "punct_removed"
    AMPERSAND_EXPANDED = "ampersand_expanded"
    ACCENTS_FOLDED = "accents_folded"
    QUOTES_NORMALIZED = "quotes_normalized"
    MARKED_UNKNOWN = "marked_unknown"

    # Structural
    DATE_SPLIT = "date_split"
    CURRENCY_MAPPED = "currency_mapped"
    COLUMN_DROPPED = "column_dropped"
    ROW_OMITTED = "row_omitted"


# --- Row-level verdicts and reasons -------------------------------------
class CleaningStatus:
    """Row-level verdict.

    TODO [CharleneKhun] (Step 3): confirm this vocabulary and record it in
    docs/data-dictionary.md so the SQL domain check has something to check.
    """

    OK = "ok"               # no rule changed or flagged this row
    CLEANED = "cleaned"     # at least one value was rewritten
    WARNING = "warning"     # kept, but a consumer should know
    EXCLUDED = "excluded"   # removed from the load-ready output


class Reason:
    """Controlled vocabulary for `warning_reason` / `exclusion_reason`."""

    MISSING_REQUIRED_ID = "missing_required_id"
    MALFORMED_ID = "malformed_id"
    MISSING_DATE = "missing_date"
    INVALID_DATE = "invalid_date"
    MISSING_CURRENCY = "missing_currency"
    AMBIGUOUS_CURRENCY = "ambiguous_currency"
    MISSING_PRICE = "missing_price"
    NON_POSITIVE_PRICE = "non_positive_price"
    MALFORMED_PRICE = "malformed_price"
    NO_VALID_FALLBACK_PRICE = "no_valid_fallback_price"

    # A MenuItem with neither a dish_id (so no fallback is reachable) nor any
    # non-zero price of its own carries no price signal by any route. Affects
    # 236 rows of 1,332,668 -- the only rows this pipeline removes.
    NO_DISH_ID_AND_NO_PRICE = "no_dish_id_and_no_price"

    # A price above the winsorization threshold. Capped, never dropped -- the
    # value is implausible for the column, but the row is still usable.
    SUSPICIOUS_EXTREME_PRICE = "suspicious_extreme_price"


class PriceSource:
    """Which rule produced `clean_price_candidate` (S3 step 4.6 fallback order).

    Resolved in SQL after the MenuItem/Dish join, not here -- see the Step 4.6
    note in docs/checklists/po-lin.md.
    """

    MENU_ITEM_PRICE = "menu_item_price"
    MENU_ITEM_HIGH_PRICE = "menu_item_high_price"
    DISH_LOWEST_HIGHEST_AVERAGE = "dish_lowest_highest_average"
    DISH_LOWEST_PRICE = "dish_lowest_price"
    DISH_HIGHEST_PRICE = "dish_highest_price"
    NO_VALID_PRICE = "no_valid_price"


# --- Null handling ------------------------------------------------------
# Raw CSVs are read with dtype=str and keep_default_na=False so that a blank
# price (P4) stays distinguishable from a 0.0 price (P5). These are the tokens
# treated as "no value" once a column is being interpreted.
NULL_LIKE_VALUES: Final[frozenset[str]] = frozenset(
    {"", " ", "nan", "NaN", "NAN", "null", "NULL", "None", "\\N", "-", "?"}
)


# --- Numeric formatting -------------------------------------------------
# Prices are written with two decimals so cents are visible: 0.0 -> "0.00".
# This is display formatting on the CSV; SQLite REAL is binary floating point
# and not exact currency (see the note in sql/06_schema_final.sql).
PRICE_DECIMAL_PLACES: Final = 2
PRICE_FORMAT: Final = f"{{:.{PRICE_DECIMAL_PLACES}f}}"


# --- Price outliers (S3 step 4.5) ---------------------------------------
# Winsorization: values above the (1 - WINSORIZE_UPPER_LIMIT) quantile are
# capped at that quantile. Rows are never dropped.
#
# RIGHT TAIL ONLY, and the asymmetry is deliberate. The left tail of a menu
# price distribution is legitimate data -- the median item is $0.40 and a $0.05
# coffee is a real price, not an error. Trimming it would inflate exactly the
# cheap menus U1 needs to rank as cheap.
#
# The limit is 0.5% on evidence, not convention. Of the 4,251 items it caps,
# only 28 (0.7%) sit on dollar-denominated menus: the right tail is almost
# entirely foreign-currency prices -- 180,000 on an Italian Lire menu is an
# ordinary price, not a transcription error -- from menus the currency filter
# already excludes from U1.
#
# Measured effect on the U1 metric (average price per menu), by menu price
# quartile, against the alternatives considered:
#
#     limit    threshold   cheapest    Q2     Q3   priciest
#     5.0%            $9      -0.2%  -0.9%  -3.3%   -13.9%
#     1.0%          $110       0.0%   0.0%   0.0%    -0.6%
#     0.5%          $300       0.0%   0.0%   0.0%    -0.1%   <- chosen
#
# A symmetric 3% trim with row removal was rejected: it shifted the priciest
# quartile by -32.0% and the cheapest by +8.7%, compressing the price range
# that U1 exists to measure.
WINSORIZE_UPPER_LIMIT: Final = 0.005

WINSORIZE_COLUMNS: Final[dict[str, tuple[str, ...]]] = {
    "dish": ("lowest_price", "highest_price"),
    "menu_item": ("price", "high_price"),
}


# --- Currency (S3 step 4.4) ---------------------------------------------
# Menu_OR.csv currently contains a single currency, "Dollars". Widening U1 scope
# means adding entries here -- but note that no FX conversion is performed, so
# any second currency is compared unconverted. See docs/cleaning-rules.md.
CURRENCY_MAP: Final[dict[str, str]] = {
    "Dollars": "USD",
}


# --- Dates (S3 step 4.3) ------------------------------------------------
# Menu_OR.csv dates arrive as ISO 8601 with a zero time part and a Z suffix,
# e.g. "1900-04-16T00:00:00Z". Split into parts for period grouping in U1.
DATE_PART_COLUMNS: Final = ("year", "month", "day")

# TODO [CharleneKhun] (Step 3): PROPOSED, pending ratification.
# Evidence: of 17,545 raw menus only 5 carry an impossible year (0001, 0190,
# 1091, 2928). The OpenRefine export already excludes them, so this band is a
# defensive re-check rather than the primary filter. Observed range in
# Menu_OR.csv is 1850-2012.
MIN_PLAUSIBLE_YEAR: Final = 1840
MAX_PLAUSIBLE_YEAR: Final = 2026


# --- Dish.name normalization (S3 step 4.2) ------------------------------
# Target charset: uppercase alphanumeric, space, apostrophe, comma.
#
# Order matters. Quotes are normalized first (so a curly apostrophe survives as
# an apostrophe rather than being folded away), then accents are folded, then
# separators become spaces, then "&" becomes a word, then anything still
# disallowed is deleted, then spaces collapse.
DISH_NAME_ALLOWED: Final[frozenset[str]] = frozenset(
    string.ascii_uppercase + string.digits + " ',"
)

# Word boundaries -- deleting these would weld words together, so they become
# spaces. "Pflaumen-Kompott" -> "PFLAUMEN KOMPOTT", not "PFLAUMENKOMPOTT".
DISH_NAME_SEPARATORS: Final = "-/():;[]{}<>|\\_~"

# Read aloud as a word, so expanded rather than dropped. 11,365 occurrences.
DISH_NAME_REPLACEMENTS: Final[dict[str, str]] = {
    "&": " AND ",
}

# Typographic variants folded to their ASCII equivalents before anything else.
DISH_NAME_QUOTE_MAP: Final[dict[str, str]] = {
    "‘": "'", "’": "'",           # single curly quotes
    "“": '"', "”": '"',           # double curly quotes
    "′": "'", "´": "'", "`": "'",  # prime, acute accent, backtick
    "–": "-", "—": "-", "−": "-",  # en/em dash, minus
    " ": " ",                           # non-breaking space
    "…": " ",                           # ellipsis
}

# A name with no salvageable ASCII content after folding -- typically a
# non-Latin script. Marked rather than dropped so the row survives for
# provenance. Affects a small tail of the 10,076 names containing non-ASCII;
# the rest fold cleanly (MEDOC, SOUP A LA CRECY).
DISH_NAME_UNKNOWN: Final = "UNKNOWN"
