-- S3 Step 6 — load the cleaned CSVs into SQLite staging.
-- Owner: Madalyn Killian  [MadalynKillian]
-- Checklist: docs/checklists/madalyn-killian.md  (Step 6)
--
-- Run:  sqlite3 data/cs513_team38.sqlite < sql/02_load_staging.sql
--
-- Inputs (from Step 4, in data/interim/):
--   Menu_cleaned.csv  MenuPage_cleaned.csv  MenuItem_cleaned.csv  Dish_cleaned.csv
--
-- WHAT THIS FILE MUST CONTAIN
--   The load itself, plus the post-load checks the checklist requires:
--   row counts per table, a CSV-to-SQLite reconciliation, typeof() checks on the
--   key cleaned columns, and null counts after loading.
--
-- THINGS THAT BITE, WORTH KNOWING BEFORE YOU START
--   - .import and .mode are sqlite3 CLI dot commands. They do not work through
--     Python's sqlite3 module or any other driver. The CLI is a separate download
--     on Windows and is NOT currently installed on this machine -- either install
--     it, or write the load in Python instead. Decide and document which.
--   - .mode csv must be set before .import, or embedded commas inside quoted
--     values shift every column to their right. Dish.name contains values like
--     ", Raw, on Half Shell" -- this corrupts data silently.
--   - .import maps CSV columns to table columns BY POSITION, not by name.
--   - .import writes '' for blank fields, never NULL.
--
-- Save the load command and the load logs as evidence.

-- TODO [MadalynKillian]: load + reconciliation + type checks
