-- S3 Step 7 — Inclusion dependency checks (IND).
-- Owner: Madalyn Killian  [MadalynKillian]
-- Checklist: docs/checklists/madalyn-killian.md  (Step 7)
--
-- Run:  sqlite3 data/cs513_team38.sqlite < sql/04_validate_ind.sql
--
-- An IND A.x subset-of B.y holds when every non-null value of A.x appears in B.y.
-- These are the joins U1 depends on: menu -> page -> item -> dish. A broken link
-- drops items out of a menu's average, which can shift its price tier -- so a
-- violation here changes the answer, it is not cosmetic.
--
-- FORM
--   One query per dependency, returning the violating rows plus their source
--   identifiers. Give each a rule ID and both a formal and a plain-English
--   statement. Compare counts across iterations.
--
-- DEPENDENCIES TO CHECK (see the checklist for the full list)
--   stg_menu_page.menu_id      subset-of  stg_menu.id
--   stg_menu_item.menu_page_id subset-of  stg_menu_page.id
--   non-null stg_menu_item.dish_id subset-of stg_dish.id
--   final_item.menu_id         subset-of  final_menu.menu_id
--
-- TWO DISTINCTIONS THE CHECKLIST ASKS FOR
--   - A missing OPTIONAL reference (dish_id is NULL) is not an IND violation --
--     NULLs are exempt. It is a different finding with a different disposition,
--     so report it separately rather than folding it into the violation count.
--   - NULL semantics: use NOT EXISTS or a LEFT JOIN ... IS NULL anti-join, not
--     "NOT IN (subquery)". If that subquery yields even one NULL, the predicate
--     evaluates to NULL rather than TRUE for every row, the query returns zero
--     rows, and a broken constraint looks like a passing one.
--
-- Export to data/reports/validation_ind_results.csv and add to queries.txt.

-- TODO [MadalynKillian]: IND rules
